### ISSUE TITLE
[feat] 타이머 기능(재생/일시정지, 이전/다음, 버튼) 구현

### ISSUE THREAD

**Issue by oceanooooo** [poplarplanet/Routiny#12]
## 🟣 Description

<img width="500" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/52116f3e-5e6e-4994-b730-3ae79b6691db">

- 현재 활성화된 루틴의 시간에 맞는 타이머를 설정합니다.

## 🟣 Todo

- [x] (TAS-50) 사용자는 현재 루틴의 남은 시간을 타이머로 볼 수 있다
  - [x] 타이머가 카운트 다운이 완료되어 00:00이 되면 다음 루틴으로 넘어간다
- [x] (TAS-55) 사용자는 [시작하기], [멈추기] 버튼으로 타이머를 재생/정지할 수 있다
- [x] (TAS-56) 루틴 타이머가 재생되고 있을 때는 [시작하기], 정지되고 있을 때는 [멈추기] 버튼이 사라진다
- [x] (TAS-53) 사용자는 [이전 루틴], [다음 루틴] 버튼으로 루틴을 넘어갈 수 있다

## 🟣 ETC

- 애플 기본 타이머의 경우 반 반자(반올림)로 시작한다
  - 애플 기본 타이머 3초: 3(0.5초) / 2(1초) / 1(1초) / 0(0.5초)
  - 갤럭시 기본 타이머 3초: 3(1초) / 2(1초) / 1(1초)

**Comment by oceanooooo** [comment]
#13 PR Merge
