### ISSUE TITLE
[feat] 프로그래스바 기능(타이머 동기화, 색상변경, 효과음) 구현

### ISSUE THREAD

**Issue by oceanooooo** [poplarplanet/Routiny#15]
## 🟣 Description

<img width="500" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/3b313126-d7d9-4ce9-a766-9fe0bd83f363"><br>
- 타이머에 맞는 프로그래스바를 구현한다
- 프로그래스바 진행 정도에 따른 효과(색상변경, 효과음)를 구현한다

## 🟣 Todo

- [x] (TAS-58) 사용자는 현재 루틴의 남은 시간과 반비례한 프로그래스바(게이지)를 볼 수 있다
- [x] (TAS-60) 프로그래스바의 1/2, 3/4, 1/1 지점에서 효과음이 나온다
- [x] (TAS-61) 프로그래스바가 1/2, 3/4 지점을 지나 구간이 바뀔 때마다 색상이 바뀐다
- [x] (TAS-50) 사용자는 현재 루틴의 남은 시간을 타이머로 볼 수 있다
  - [x] (추가) 타이머에 1초를 추가하여 00:00초까지 보여준다
