### ISSUE TITLE
[feat] 타이머세팅뷰 - 리스트 커스텀의 기능 구현 

### ISSUE THREAD

**Issue by zyeongPark** [poplarplanet/Routiny#19]
## 🟣 Description

타이머세팅뷰의 리스트에 있는 기능을 구현합니다. 

## 🟣 Todo

- [x] TAS-39: 사용자는 편집버튼을 눌러 서비스에서 기본적으로 제공하는 4가지 루틴의 시간을 1-59분 내로 설정할 수 있다
- [x] TAS-51: 사용자는 개별 루틴의 순서를 조정할 수 있다
- [x] TAS-52: 사용자는 기본 루틴 중 토글을 활용하여 사용 여부를 설정할 수 있다
- [x] TAS-72: 사용자는 루틴 총 소요 시간을 확인할 수 있다
- [x] TAS-73: 편집 버튼 클릭 시 루틴 계획표를 짜는 기능(2.0 루틴뷰에 있는 기능과 동일) 
- [x] TAS-74: 편집버튼을 클릭하면 완료버튼으로 명칭이 변경된다
