### ISSUE TITLE
[feat] AppStorage를 활용해 앱 내 저장하는 기능 구현

### ISSUE THREAD

**Issue by jaelyung** [poplarplanet/Routiny#21]
## 🟣 Description

1. TimerSettingView에서 사용자가 변경한 정보를 AppStorage에 저장하는 기능을 구현합니다.
2. 앱에서 기본적으로 제공해야 하는 루틴 카테고리를 AppStorage에 저장하고, 앱이 실행될 때 불러올 수 있는 기능을 구현합니다.

## 🟣 Todo

- [x] TAS-81 사용자가 변경한 루틴 시간을 앱 내에 저장한다
- [x] TAS-80 앱 최초 실행할 때 기본으로 제공하는 루틴의 명칭, 분, 순서, 사용 여부가 ~~AppStorage~~ sqlite에 저장된다
- [x] TAS-57 사용자는 설정한 닉네임을 화면에서 볼 수 있다
- [x] TAS-71 사용자는 설정한 닉네임을 화면에서 볼 수 있다

**Comment by jaelyung** [comment]
#29
