### ISSUE TITLE
[feat] 타이머뷰 루틴목록 완료여부 체크 및 화면 BGM

### ISSUE THREAD

**Issue by oceanooooo** [poplarplanet/Routiny#22]
## 🟣 Description

 <img width="800" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/f2048cd1-0d3f-44e2-b373-c38584b69b2d"><br>
- 루틴 목록에서 루틴 완료 여부를 확인할 수 있다
- 타이머뷰에서 BGM가 무한 재생된다
- 루틴 무한 루프 기능을 없앤다

## 🟣 Todo

- [x] (TAS-54) 첫번째 루틴은 [이전 루틴], ~마지막 루틴은 [다음 루틴] 버튼이~ 비활성화 된다
  - [x] (PR) [다음] 버튼은 항시 활성화된다
- [x] (TAS-92) 타이머 화면에서는 배경음이 `계속` 나온다
  - [x] (PR) 타이머 재생/일시정지 상태에 배경음 재생/일시정지 상태가 동기화된다
- [x] (TAS-100) 루틴 목록에서 완료된 루틴은 이미지가 변경된다
- [x] (TAS-101) 이전 루틴으로 이동할 경우 해당 루틴은 완료 처리가 취소된다
- [x] (TAS-102) 다음 루틴으로 이동할 경우 이전 루틴은 완료 처리가 된다
- [x] (PR) 타이머 시작 전 프로그래스바는 채워진 것이 없는 비활성화 상태이다

**Comment by oceanooooo** [comment]
#23 PR Merged
