### ISSUE TITLE
[feat] 타이머뷰 Hi-Fi 레이아웃 작업

### ISSUE THREAD

**Issue by oceanooooo** [poplarplanet/Routiny#26]
## 🟣 Description

<img width="500" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/0737da0f-232a-40ad-ba47-42450a573cde"><br>
|참고 이미지(타이머 시작뷰)|참고 이미지(타이머 완료뷰)|
|:---:|:---:|
|<img width="300" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/fe670be0-4775-402f-a020-c08b14bdeed2">|<img width="300" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/3097f343-98c8-45d9-a924-140de1ffa3f3">|

## 🟣 Todo

- [x] Hi-Fi 적용
  - [x] 루틴 목록 레이아웃에 Hi-Fi 적용
    - [x] 루틴 목록의 top은 고정
      - 타이머 기본뷰, 종료 예상 시간이 추가된 타이머 시작/완료 뷰 모두 동일한 top을 가짐
  - [x] 프로그래스바, 타이머 컨트롤러 레이아웃에 Hi-Fi 적용
  - [x] 현재루틴 정보(타이틀, 소요시간, 이미지, 타이머) Hi-Fi 적용 (without 그래픽)
- [x] 기능수정
  - [x] 타이머 초기값 실제 시간으로 변경
  - [x] 타이머 100% 완료 후 멘트 시간만큼 딜레이 추가
  - [x] 루틴 별 타이머 구간 사운드 설정

## 🟣 ETC

- Hi-Fi를 맞추기 위해 어느 정도 하드 코딩이 예상됩니다.
  - 루틴목록의 위치, 현재 루틴 소요시간의 위치
- refactoring 시 위치를 우측 하단으로 밀어넣는 extension을 사용하면 뷰의 코드가 깔끔할 듯 합니다.

**Comment by oceanooooo** [comment]
#32 PR Merged
