### ISSUE TITLE
[feat] 루틴뷰 레이아웃 및 기능 구현

### ISSUE THREAD

**Issue by zyeongPark** [poplarplanet/Routiny#28]
## 🟣 Todo

 **<루틴뷰>**
- [x] 루틴뷰에 있는 커스텀 리스트 레이아웃 구현 
- [x] 편집 버튼 클릭 시 edit 모드로 전환될 수 있도록 함
- [x] 현재 시간 화면 출력
- [x] 루틴시작하기 버튼 클릭 시 그래픽 A,B 전환

**<타이머 세팅뷰>**
- [x] 총 루틴 소요 시간 화면 출력(단, 수정 불가)
- [x] 휠피커로 루틴별 시간 변경 시 총 루틴 소요 시간도 변경

## 🟣 ETC

- 구현 미완료 부분은 추가로 이슈 파서 진행하겠습니다.
