### ISSUE TITLE
[feat] 타이머세팅뷰, 루틴뷰에서 기능 구현이 되지 않았던 부분 수정 

### ISSUE THREAD

**Issue by zyeongPark** [poplarplanet/Routiny#34]
## 🟣 Todo

- [x] 토글 true일 때만 총 소요시간 계산 
- [x] 휠피커에 의해 변한 루틴 총 소요시간 반영 (in 루틴뷰) 
- [x] 휠피커가 아니라, 완료 버튼 클릭 시 총 소요 시간 변화 
- [x] 총 소요시간을 n시간 n 분으로 표시 
- [x] 토글은 기본 1개 이상 선택되어야 하는 것으로 
    - [x] 만약 0개가 선택된다면 다음 버튼 비활성화 되도록 구현 
- [x] 토글 off의 경우 비활성화 UI는 유지하며 시간, 순서 변경 가능 

## 🟣 ETC

spirnt2에서 완성하지 못했던 기능을 구현합니다.
