### ISSUE TITLE
[feat] 타이머뷰, 준비뷰, 완료뷰 기능(재생/정지, 종료 예상 시각, 단계 넘김) 구현

### ISSUE THREAD

**Issue by oceanooooo** [poplarplanet/Routiny#37]
## 🟣 Description

<img width="500" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/5f006717-e942-432a-8e10-180b4b11e612"><br>
<img width="500" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/06cb4dd9-9a14-40c8-8443-05d8232a5f75"><br>
<img width="500" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/fdb8a04c-2485-4a63-80ef-0b4c92a606eb"><br>

## 🟣 Todo

**[타이머뷰]**
- [x] (TAS-127) 타이머뷰에서 종료 예상 시각이 항상 나온다
- [x] (TAS-128) 루틴 일시정지 시 종료 예상 시각이 실시간으로 다시 계산된다
- [x] (TAS-165) 마지막 루틴이 종료되거나 마지막 루틴에서 [다음] 버튼을 누르면 타이머완료뷰로 넘어간다

**[타이머준비뷰]**
- [x] (TAS-121) 4초 카운트 다운 시 초마다 이미지가 변경된다
- [x] (TAS-124) 일시정지 시 재생중이던 효과음도 일시정지 된다
- [x] (TAS-169) 일시정지 시 종료 예상 시각이 실시간으로 다시 계산된다

**[타이머완료뷰]**
- [x] (TAS-108) 전체 루틴 완료 후 사용자는 완료 메시지가 적힌 이미지를 5초간 볼 수 있다
- [x] (TAS-129) 타이머완료뷰에서 5초 후에 루틴뷰로 자동으로 넘어간다

## 🟣 ETC

- Hi-Fi 단계에서 단축된 효과음(루틴 타이머 종료 음성), 이미지로 변경하겠습니다.

**Comment by oceanooooo** [comment]
타이머준비뷰에서 타이머가 재생중일 때 종료예상시각에 현재 루틴의 소요시간이 계산에서 누락되던 문제 해결했습니다.
|수정전|수정후|
|:---:|:---:|
|<img width="400" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/b720e05d-85fb-48dd-9fd8-608090955914">|<img width="400" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/b8c6e3b7-2792-4307-9340-05cfaabda8a4">|

**Comment by oceanooooo** [comment]
#38 PR Merged
