### ISSUE TITLE
[feat] SettingView Hi-Fi 레이아웃 생성

### ISSUE THREAD

**Issue by jaelyung** [poplarplanet/Routiny#40]
## 🟣 Description

SettingView 레이아웃을 Hi-Fi에 맞춰 구성합니다.

## 🟣 Todo

- [x] Hi-Fi 디자인 레이아웃 구현
- [x] TAS-109 사용자는 설정하기 화면에서 기존에 저장한 닉네임과 연령을 확인할 수 있다
- [x] TAS-122 사용자는 설정하기 화면에서 기존에 저장한 닉네임과 연령을 수정할 수 있다. 
- [x] 실행음 배경음, 효과음 토글 생성
- [x] TAS-113 사용자는 포플러플래닛 홈페이지 방문하기 버튼을 눌러 해당하는 외부 링크로 접근할 수 있다

**Comment by jaelyung** [comment]
#49
