### ISSUE TITLE
[feat] TimerSettingView HiFi 

### ISSUE THREAD

**Issue by zyeongPark** [poplarplanet/Routiny#42]
## 🟣 Todo

- [x] wheelPicker 배경색 변경 (white, 스트로크 없음)
- [x] 이미지 추가 (txt_bubble로 3가지 이미지 합친 것 사용) 
- [x] 컬러 추가 
- [x] 폰트 변경 
- [x] 네비게이션 바 "뒤로", "루틴시작하기" 버튼 커스텀 

## 🟣 ETC

**5.10 수정 사항** 
- [x] A_txt_bubble, B_txt_bubble, onboarding 이미지 에셋 삭제 
- [x] txt_bubble 이미지 에셋 추가 
- [x] 실기기 미동작으로 인해 데이터 경로 코드 수정
