### ISSUE TITLE
[feat] 타이머뷰(+준비,완료) 배경색 변경 기능 및 Hi-Fi 적용

### ISSUE THREAD

**Issue by oceanooooo** [poplarplanet/Routiny#44]
## 🟣 Description

<img width="500" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/ad50b5df-b447-4b03-8a49-574040b8ae50"><br>
<img width="500" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/daf3bdde-4385-4ae4-a475-99930b7774ed"><br>
<img width="500" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/63508dd4-0ec3-4926-9bc1-87fcb06acca5"><br>

## 🟣 Todo

- [x] (TAS-145) Hi-Fi(색상, 이미지, 폰트크기, 폰트두께, 패딩, 정렬) 적용
  - [x] (TAS-150) 타이머에서 루틴이 짝수인지, 홀수인지에 따라 배경 색상이 다르고 타이머 준비뷰도 배경색이 다르다.
  - [x] 타이머 컨트롤러
  - [x] 프로그래스바
  - [x] 루틴 이미지
  - [x] 루틴 타이틀과 시간
  - [x] 준비뷰/완료뷰 그래픽
  - [x] 루틴목록
- [x] 이미지 에셋 추가
- [ ] 수정된 음성 파일로 변경

## 🟣 ETC

- 루틴 목록의 작은 이미지 에셋이 루틴뷰에서도 사용됩니다. 
  - 작업 속도를 봐서 이 이슈의 PR이 먼저 close될 것 같으면 노티 후 이 이슈에서 에셋에 추가하겠습니다.
- 루틴 목록에서는 패딩에 0.5 단위의 소수점 값이 사용됩니다. (확인 결과 의도된 내용)
- 피그마에서 깔끔하지 않은 소수점으로 나오는 값은 stroke의 영향인지 살펴봅니다.
  - 특이사항이 있는 값은 피그마에서 빨간 글씨로 표시하겠습니다.
- 동일한 이름의 에셋(사운드 파일)을 추가 시 파일 참조가 어떻게 작동하는지 확인하겠습니다.

**Comment by oceanooooo** [comment]
#46 PR Merged
