### ISSUE TITLE
[feat] 사용자 별명 입력 글자수 제한 문구 사라지는 기능 & 컬러변경 & 패딩값 변경

### ISSUE THREAD

**Issue by jaelyung** [poplarplanet/Routiny#45]
## 🟣 Description

- 사용자가 5글자 이상 입력하려고 시도했을 때 글자수 제한문구를 출력하고나서 다시 사용자가 5글자 미만으로 입력하거나 전체삭제를 누르면 문구가 사라지는 기능을 구현합니다.
- 컬러에셋 명칭 변경을 적용합니다.

## 🟣 Todo

- [x] 전체 삭제시 글자수 제한 문구 사라짐
- [x] 4자 이하로 입력시 글자수 제한 문구 사라짐
- [x] 컬러 변경
- [x] 네비게이션 패딩값 제거

**Comment by jaelyung** [comment]
#55
