### ISSUE TITLE
[feat] 사용자 닉네임, 연령 정보 입력 및 저장기능

### ISSUE THREAD

**Issue by jaelyung** [poplarplanet/Routiny#5]
## 🟣 Description

AddKidView의 메인 기능인 아이 별명 입력, 아이 나이 선택 UI를 구성합니다.
사용자가 입력한 내용을 AppStorage에 저장합니다. 

## 🟣 Todo

- [x] TAS-37 사용자는 닉네임을 기록할 수 있다
- [x] TAS-43 사용자는 연령 선택지를 한개만 선택할 수 있다
- [x] TAS-79 입력된 닉네임과 연령은 앱 내에 저장된다

**Comment by jaelyung** [comment]
#9 PR Merge
