### ISSUE TITLE
[feat] 사용환경(라이트모드, 가로모드) 설정 및 타이머뷰 문제 해결

### ISSUE THREAD

**Issue by oceanooooo** [poplarplanet/Routiny#50]
## 🟣 Todo

- [x] (TAS-97) 다크모드 제외
- [x] (TAS-106) 가로모드만 사용 가능
- [x] 타이머 100% 달성 이후 발생하는 에러 해결
  - `invalid frame dimension (negative or non-finite)`
- [x] 타이머뷰 내비게이션 백버튼 커스텀 적용
- [x] 컬러 네이밍에서 카운팅 누락된 것 수정
- [x] 이미지 에셋 수정
- [x] 사운드 리소스 수정

**Comment by oceanooooo** [comment]
#56 PR Merged
