### ISSUE TITLE
[feat] 루틴뷰 Hi-Fi 디자인 

### ISSUE THREAD

**Issue by zyeongPark** [poplarplanet/Routiny#53]
## 🟣 Todo

**레이아웃 디자인 입히기**
- [x]  wheelPicker 배경색 변경 (white, 스트로크 없음)
- [x]  컬러 변경 (배경, 오브젝트, 폰트) 
- [x]  pretendard로 폰트 변경 
- [x] 루틴 전, 루틴 후 이미지 추가 (R_before, R_done)
- [x] Lo-Fi -> Hi-Fi 디자인 및 로직 변경된 부분 수정 (종료 예정 시각 출력) 

**추가 구현** 
- [x]  편집/완료버튼 OnPressed 기능 구현 (타이머 세팅뷰에도 추가) 
- [x] 타이머 세팅뷰 레이아웃 디테일 수정
