### ISSUE TITLE
[refactor] 타이머세팅뷰 QA 피드백 반영

### ISSUE THREAD

**Issue by zyeongPark** [poplarplanet/Routiny#59]
## 🟣 Todo

- [x]  편집 상태가 아닐 경우 루틴 수정 불가
- [x] 휠피커 색 변환 (white → beige100)
- [x] [편집] 버튼 길게 누르거나 짧게 눌러도 반투명해지지 않도록 수정 → 자연스럽게 전환 가능
- [x] 캡슐에 opacity(0.5) 적용
- [x] 리스트 테두리 굵기: figma에는 1로 명시 되어있지만 2로 수정
- [x]  루틴 목록 영역의 4방향 padding 값과 루틴 사이의 padding 간격이 다름
- [x] 텍스트 간격 수정
- [ ]  isSettingDone 조건 있어서 타이머세팅뷰->루틴뷰 전환 효과 없음
