### ISSUE TITLE
[feat] 현재 루틴 정보(이름, 소요시간, 이미지), 루틴 목록 출력 기능

### ISSUE THREAD

**Issue by oceanooooo** [poplarplanet/Routiny#6]
## 🟣 Description

<img width="500" alt="image" src="https://github.com/poplarplanet/Routiny/assets/127754551/85297282-e84e-412b-9a9d-5c16b2576fdb">

## 🟣 Todo

- [x] (TAS-40) 사용자는 현재 루틴의 이름과 소요시간을 화면에서 확인할 수 있다
- [x] (TAS-70) 사용자는 현재 루틴의 이미지를 확인할 수 있다
- [x] (TAS-65) 사용자는 루틴 목록(이름, 이미지)을 확인할 수 있다
- [x] (TAS-66) 현재 루틴만 루틴 목록에서 강조되어(활성화) 있다

## 🟣 ETC

- 데이터 연결이 되지 않은 단계이기 때문에 더미 데이터로 작업합니다.
- 더미 데이터는 빠르게 작업이 가능한 형태로 사용합니다.

**Comment by oceanooooo** [comment]
#11 PR Merge
