### ISSUE TITLE
[feat] 타이머뷰 중간점검 피드백 반영

### ISSUE THREAD

**Issue by oceanooooo** [poplarplanet/Routiny#60]
## 🟣 Todo

- [x] 타이머뷰 alert의 '종료하기' 버튼 빨간색으로 수정
- [x] 준비뷰 마지막 음성, 타이머뷰 마지막 음성 파일 수정 반영
- [ ] 타이머 100% 달성 시 타이머 내용물 'GOOD' 텍스트에서 웃는 이미지로 수정
- [x] 완료뷰 완료 음성 삽입

**Comment by oceanooooo** [comment]
#62 PR Merged
