### ISSUE TITLE
[fix] 루틴뷰 QA 피드백 반영

### ISSUE THREAD

**Issue by zyeongPark** [poplarplanet/Routiny#61]
## 🟣 Todo

- [x] 편집 상태가 아닐 경우 루틴 수정 불가 
- [x] off 인 루틴의 시간은 총 소요시간에 반영 x
- [x] 편집 중 완료(저장) 없이 종료하면 데이터가 변경되기 전 값으로 나옴
- [x] 휠피커 배경 수정 
- [x] 네비게이션 스택 문제라 [<되돌아오기>] 버튼 위치 고정
- [x] 편집 중일 때 설정뷰 갔다오면 완료뷰로 나옴
- [x] 자정을 기준으로 루틴 완료 리셋 
- [ ] 편집이 완료되지 않은 상태로 앱을 껐다 실행해도 완료되지 않은 시점에서 바뀐 총 시간과 루틴 종료 예정 시각으로 나옴
- [ ] 완료를 누르면 정상적으로 계산됨

## 🟣 ETC

- [x] 실기기와 시뮬레이터 모두 동작 이상 없도록 코드 수정할 예정입니다. 
- [x] 리스트 순서 조정 매끄럽지 못한 것 : list custom과 함께 이후 MVP 에서 수정 예정
