### ISSUE TITLE
[feat] ParentalGateView 개발

### ISSUE THREAD

**Issue by jaelyung** [poplarplanet/Routiny#63]
## 🟣 Description

설정하기 버튼을 누를 때마다 랜덤한 수학 문제를 제시해 페이지 이동의 제한을 주는 ParentalGateView의 레이아웃을 개발합니다.

## 🟣 Todo

- [x] TAS-175 화면 레이아웃 개발
- [x] TAS-195 랜덤 뺄셈 문제를 화면에 출력
- [x] TAS-196 정답이 음수가 되지 않도록 큰 수가 항상 왼쪽에 출력
- [x] TAS-186 숫자 버튼을 선택해 0~99 숫자를 입력하는 기능 구현
- [x] 0을 입력할 때 발생할 수 있는 예외처리
- [x] TAS-209 정답은 1~99 사이의 숫자로만 구성되도록 구현
- [x] TAS-188 확인 버튼을 선택해 입력된 수가 정답/오답인지 판단하는 기능
- [x] TAS-189 정답/오답 판단되었을 경우 수식 색이 초록/빨강으로 변경되는 기능
- [x] TAS-191 오답 시 1초 지연 후 새로운 문제로 자동 리셋하는 기능
- [x] TAS-190 정답을 맞추면 1초 지연 후 설정뷰로 자동으로 이동하는 기능
- [x] TAS-199 되돌아가기 버튼을 누르면 RoutineView로 이동하는 기능

**Comment by jaelyung** [comment]
#72
