### ISSUE TITLE
[fix] AddKidView 테스트 피드백 반영

### ISSUE THREAD

**Issue by jaelyung** [poplarplanet/Routiny#65]
## 🟣 Todo

- [x] TC-23 전체삭제 버튼 위치 고정
- [x] TC-74 화면 스크롤 크기 변경
- [x] TC-74 키보드 동작시에만 스크롤 작동
- [ ] TC-74 네비게이션 툴바 투명도 (Optional)
- [x] TC-25 이미 선택된 연령 버튼은 클릭되지 않도록 함

**Comment by jaelyung** [comment]
#69 
툴바에 기능 적용 불가능으로 Optional task는 패스함
